### PR TITLE
feat: Improve UI by printing errors in a separate queue, on exit and small touch-ups

### PR DESCRIPTION
**Pull request by grufkork**
I ran into a couple of problems with the nicer UI, namely that errors disappeared too quickly in the event list. Now they have a separate queue, as well as all errors being printed when exiting. Other than that there's a few small general touch-ups just to make everything look nicer.

image

- Separate display for errors, as errors disappeared too quickly
- Overall nicer formatting
- HH:MM:SS timestamps
- Separated skipped tracks from "real" errors

### CODE REVIEW

**Comment by grufkork** [comment]
Why `invalid type: null` appears however, I have no idea, probably a separate issue. It was the same songs every time.

**Comment by oSumAtrIX** [comment]
What happens if the already downloaded list gets so long it doesn't fit on screen anymore?

**Comment by grufkork** [comment]
Both the top and bottom lists are capped, just as before, to show the 10 or 5 most recent messages respectively. Top is "Already downloaded"s and OKS (there just weren't any OKs when I screenshotted), bottom is fatal errors. When the program exits it dumps the entire list of errors. 

I'm considering instead dumping the entire log (not just errors) at the end, but keeping it behind a flag. 

You could add a setting for message list length, but for any reasonable number of threads there should always be fewer than 30 lines on screen at any moment, which I think is reasonable.

**Comment by oSumAtrIX** [comment]
Thanks

**Pull request merged**
